################
## PRODUCTION ##
################

# Build another image named production
FROM node:16.14.2-slim AS production


# Set Working Directory
WORKDIR /usr/src/app/sancon-clock-api

# Copy all from development stage
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Set node env to prod
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Run app
CMD [ "node", "dist/main" ]